build:
  image: xataz/docker-client:1.12.5
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/xataz/.docker/config.json:/home/docker/.docker/config.json
    - /home/xataz/.docker/config.json:/root/.docker/config.json
  environment:
    - UID=1000
    - GID=1000
    - TERM=xterm
  commands:
    - chmod +x gen_rootfs.sh
    - ./gen_rootfs.sh -v 2.7 -b xataz/alpine -p
    - ./gen_rootfs.sh -v 3.0 -b xataz/alpine -p
    - ./gen_rootfs.sh -v 3.1 -b xataz/alpine -p
    - ./gen_rootfs.sh -v 3.2 -b xataz/alpine -p
    - ./gen_rootfs.sh -v 3.3 -b xataz/alpine -p
    - ./gen_rootfs.sh -v 3.4 -b xataz/alpine -p
    - ./gen_rootfs.sh -v 3.5 -b xataz/alpine -p
    - ./gen_rootfs.sh -v edge -b xataz/alpine -p
  tty: true